server:
  port: 8762

spring:
  application:
    name: service-hi
  zipkin:
    base-url: http://localhost:9411


eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://192.168.3.210:8761/eureka/