server:
  port: 8761

eureka:
  instance:
    hostname: peer3
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer1:8759/eureka/,http://peer2:8760/eureka/,http://peer3:8761/eureka/

spring:
  application:
    name: eurka-server